Improve build-unix script

diff --git a/build-unix b/build-unix
--- a/build-unix
+++ b/build-unix
@@ -17,12 +17,18 @@ YELLOW='\033[1;33m'
 NC='\033[0m' # No Color
 SUCCESS=-1
 
+if ! command -v cmake --version >/dev/null 2>&1
+then
+    echo -e "❗ ${RED}CMake could not be found. Make sure that it is installed on your system.${NC}"
+    exit 1
+fi
+
 # do this better!
 if [ $(uname) = "Darwin" ]; then
   echo "patchelf not needed."
 else
   if ! [ -x "$(command -v patchelf)" ]; then
-    echo -e "${RED}patchelf could not be found. Make sure that it is installed on your system.${NC}"
+    echo -e "❗ ${RED}patchelf could not be found. Make sure that it is installed on your system.${NC}"
     exit 1
   else
     echo "Found patchelf."
